# Generated by Django 3.2.7 on 2021-10-07 12:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_startup_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startup_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=5),
        ),
    ]
