# Generated by Django 3.2.7 on 2021-10-07 12:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_startup_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='startup_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large')], max_length=5),
        ),
    ]
